#pragma config(Sensor, in8,    lightSensor,    sensorReflection)
#pragma config(Sensor, dgtl6,  sonarSensor,    sensorSONAR_cm)
#pragma config(Motor,  port2,           leftMotor,     tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port3,           rightMotor,    tmotorServoContinuousRotation, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//+++++++++++++++++++++++++++++++++++++++++++++| MAIN |+++++++++++++++++++++++++++++++++++++++++++++++
task main()
{
  int speed;            // Will hold a speed for the motors.
  int sonar_value;      // Will hold the current reading of the sonar sensor.
  int distance = 25;    // Specified distance to be at 25 centimeters.

  while(true)
  {
    sonar_value = SensorValue(sonarSensor);   // Store the current reading from the Sonar Sensor to 'sonar_value'.

    clearLCDLine(0);                          /* Display the    */
    displayLCDPos(0,0);                       /* reading of the */
    displayNextLCDString("Sonar: ");          /* Sonar Sensor   */
    displayNextLCDNumber(sonar_value);        /* on line 0.     */

    if(sonar_value < 0)                       // If the object is out of range: (returns -1)
    {
      speed = 127;                            // Set 'speed' to full speed ahead!
    }
    else
    {
      speed = (sonar_value - distance)*2;     // Set 'speed' equal to the 'sonar_value' minus desired 'distance'.
    }

    clearLCDLine(1);                          /* Display the    */
    displayLCDPos(1,0);                       /* current speed  */
    displayNextLCDString("Speed: ");          /* of the motors  */
    displayNextLCDNumber(speed);              /* on line 1.     */

    motor[leftMotor]  = speed;                /* Set both the left and right */
    motor[rightMotor] = speed;                /* motors to run at 'speed'.   */

    wait1Msec(100);                           // Take 10 readings per second.
  }
}
//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
